# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'opennft\ui\rtQAUI.ui'
#
# Created by: PyQt5 UI code generator 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_rtQA(object):
    def setupUi(self, rtQA):
        rtQA.setObjectName("rtQA")
        rtQA.resize(1435, 389)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(rtQA.sizePolicy().hasHeightForWidth())
        rtQA.setSizePolicy(sizePolicy)
        self.volumeCheckBox = QtWidgets.QCheckBox(rtQA)
        self.volumeCheckBox.setGeometry(QtCore.QRect(10, 60, 70, 17))
        self.volumeCheckBox.setObjectName("volumeCheckBox")
        self.layoutWidget_2 = QtWidgets.QWidget(rtQA)
        self.layoutWidget_2.setGeometry(QtCore.QRect(730, 400, 641, 221))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.tdPlot = QtWidgets.QVBoxLayout(self.layoutWidget_2)
        self.tdPlot.setContentsMargins(0, 0, 0, 0)
        self.tdPlot.setObjectName("tdPlot")
        self.layoutWidget_3 = QtWidgets.QWidget(rtQA)
        self.layoutWidget_3.setGeometry(QtCore.QRect(730, 660, 641, 221))
        self.layoutWidget_3.setObjectName("layoutWidget_3")
        self.rdPlot = QtWidgets.QVBoxLayout(self.layoutWidget_3)
        self.rdPlot.setContentsMargins(0, 0, 0, 0)
        self.rdPlot.setObjectName("rdPlot")
        self.layoutWidget_5 = QtWidgets.QWidget(rtQA)
        self.layoutWidget_5.setGeometry(QtCore.QRect(80, 660, 641, 221))
        self.layoutWidget_5.setObjectName("layoutWidget_5")
        self.fdPlot = QtWidgets.QVBoxLayout(self.layoutWidget_5)
        self.fdPlot.setContentsMargins(0, 0, 0, 0)
        self.fdPlot.setObjectName("fdPlot")
        self.layoutWidget_4 = QtWidgets.QWidget(rtQA)
        self.layoutWidget_4.setGeometry(QtCore.QRect(80, 400, 641, 219))
        self.layoutWidget_4.setObjectName("layoutWidget_4")
        self.mcPlot = QtWidgets.QVBoxLayout(self.layoutWidget_4)
        self.mcPlot.setContentsMargins(0, 0, 0, 0)
        self.mcPlot.setObjectName("mcPlot")
        self.mcLabel = QtWidgets.QLabel(rtQA)
        self.mcLabel.setGeometry(QtCore.QRect(80, 370, 641, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.mcLabel.setFont(font)
        self.mcLabel.setText("")
        self.mcLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.mcLabel.setObjectName("mcLabel")
        self.tdLabel = QtWidgets.QLabel(rtQA)
        self.tdLabel.setGeometry(QtCore.QRect(730, 370, 641, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.tdLabel.setFont(font)
        self.tdLabel.setText("")
        self.tdLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.tdLabel.setObjectName("tdLabel")
        self.fdLabel = QtWidgets.QLabel(rtQA)
        self.fdLabel.setGeometry(QtCore.QRect(80, 630, 641, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.fdLabel.setFont(font)
        self.fdLabel.setText("")
        self.fdLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.fdLabel.setObjectName("fdLabel")
        self.rdLabel = QtWidgets.QLabel(rtQA)
        self.rdLabel.setGeometry(QtCore.QRect(730, 630, 641, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.rdLabel.setFont(font)
        self.rdLabel.setText("")
        self.rdLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.rdLabel.setObjectName("rdLabel")
        self.comboBox = QtWidgets.QComboBox(rtQA)
        self.comboBox.setGeometry(QtCore.QRect(10, 10, 121, 22))
        self.comboBox.setEditable(False)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.tsCheckBox = QtWidgets.QCheckBox(rtQA)
        self.tsCheckBox.setGeometry(QtCore.QRect(10, 40, 70, 17))
        self.tsCheckBox.setObjectName("tsCheckBox")
        self.layoutWidget = QtWidgets.QWidget(rtQA)
        self.layoutWidget.setGeometry(QtCore.QRect(140, 10, 1281, 371))
        self.layoutWidget.setObjectName("layoutWidget")
        self.snrPlot = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.snrPlot.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.snrPlot.setContentsMargins(0, 0, 0, 0)
        self.snrPlot.setObjectName("snrPlot")
        self.smoothedCheckBox = QtWidgets.QCheckBox(rtQA)
        self.smoothedCheckBox.setGeometry(QtCore.QRect(30, 80, 70, 17))
        self.smoothedCheckBox.setObjectName("smoothedCheckBox")

        self.retranslateUi(rtQA)
        self.comboBox.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(rtQA)

    def retranslateUi(self, rtQA):
        _translate = QtCore.QCoreApplication.translate
        rtQA.setWindowTitle(_translate("rtQA", "RTQA"))
        self.volumeCheckBox.setText(_translate("rtQA", "Volume"))
        self.comboBox.setItemText(0, _translate("rtQA", "SNR"))
        self.comboBox.setItemText(1, _translate("rtQA", "MCMD"))
        self.comboBox.setItemText(2, _translate("rtQA", "CNR"))
        self.comboBox.setItemText(3, _translate("rtQA", "Spikes"))
        self.comboBox.setItemText(4, _translate("rtQA", "Trend"))
        self.comboBox.setItemText(5, _translate("rtQA", "Steps"))
        self.tsCheckBox.setText(_translate("rtQA", "Time series"))
        self.smoothedCheckBox.setText(_translate("rtQA", "Smoothed"))


